### ISSUE TITLE
Keypad prefab back button doesn't work

### ISSUE THREAD

**Issue by ModerateWinGuy** [jetdog8808/Jetdogs-Prefabs-Udon#1]
I've been using the keypad prefab and it works well and can trigger the event, but the backspace button doesn't seem to work, so unfortunately if you type something incorrectly your out of luck.

**Comment by jetdog8808** [comment]
Sorry for some reason I didn't get a notification of this. This issue should have been solved with update V1.1.1
Vrchat implemented a ui whitelist which caused the problem.
